import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/Layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
         <div className="flex min-h-screen">
            {/* Contenido Principal */}
            <div className="flex-1 flex flex-col w-full min-w-0">
              {/* Header Top */}
              
            <div className="sticky  top-0 left-0 right-0 z-40">
               <NavBar />
            </div>
              {/* Contenido de la página */}
              <main className="min-h-screen bg-gray-100 shadow-lg border">
                {children}
              </main>
            </div>
          </div>
      </body>
    </html>
  );
}
